import { createSlice, PayloadAction } from '@reduxjs/toolkit'
import { <%= interfaceName %> } from './types'

/**
 * Initial state for the <%= sliceName %> slice
 */
const initialState: <%= interfaceName %> = <%- initialStateString %>

/**
 * Redux slice for <%= sliceName %> state management
 * Auto-generated by react-state-cli
 */
const <%= sliceName %>Slice = createSlice({
  name: '<%= sliceName %>',
  initialState,
  reducers: {
<%- actionCases %>
  }
})

export const { <%= actionExports %> } = <%= sliceName %>Slice.actions
export default <%= sliceName %>Slice.reducer
